version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  php:
    image: php:7.4-fpm
    restart: always
    depends_on:
      - db
    ports:
      - "9000:9000"  
    volumes:
      - ./site:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - php
    volumes:
      - ./site:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site:/var/www/html

volumes:
  site:
