version: "3.9"

services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_SORT_BUFFER_SIZE: 8M
      MYSQL_MAX_USER_CONNECTIONS: 100
      MYSQL_THREAD_CACHE_SIZE: 10
      MYSQL_INNODB_BUFFER_POOL_SIZE: 820M
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    resources:
      limits:
        cpus: "0.9"
        memory: 1750M
    volumes:
      - db-data:/var/lib/mysql:rw

  php:
    image: php:8.3-fpm
    restart: always
    depends_on:
      - db  
    volumes:
      - site:/var/www/html:rw
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress_db

  wordpress:
    image: wordpress:6.4.3
    restart: always
    depends_on:
      - php
    volumes:
      - site:/var/www/html:rw
    ports:
      - "80:80"  
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress_db

  nginx:
    image: nginx:1.25.4
    restart: always
    ports:
      - "1025:80"
    depends_on:
      - php
    volumes:
      - site:/var/www/html:rw
      - nginx:/etc/nginx:rw

volumes:
  db-data:
  nginx:
  site:

